buildscript {
    ext.kotlinVersion = '2.1.0'
    ext.navigationVersion = '2.8.4'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Define versions in a single place
ext {
    // Sdk and tools
    minSdkVersion = 21
    targetSdkVersion = 35
    compileSdkVersion = 35

    // App dependencies
    androidXVersion = '1.0.0'
    androidXTestCoreVersion = '1.6.1'
    androidXTestExtKotlinRunnerVersion = '1.2.1'
    androidXTestRulesVersion = '1.2.0'
    androidXAnnotations = '1.9.1'
    appCompatVersion = '1.7.0'
    archLifecycleVersion = '2.8.7'
    archTestingVersion = '2.2.0'
    coroutinesVersion = '1.5.2'
    cardVersion = '1.0.0'
    coroutinesVersion = '1.9.0'
    dexMakerVersion = '2.28.4'
    espressoVersion = '3.6.1'
    fragmentVersion = '1.8.5'
    hamcrestVersion = '1.3'
    junitVersion = '4.13.2'
    materialVersion = '1.12.0'
    mockitoVersion = '5.14.2'
    multiDexVersion = '2.0.1'
    recyclerViewVersion = '1.3.2'
    robolectricVersion = '4.14.1'
    roomVersion = '2.6.1'
    rulesVersion = '1.0.1'
    swipeRefreshLayoutVersion = '1.1.0'
    timberVersion = '5.0.1'
    truthVersion = '1.1.2'
}
